export const ProductsMock = [
  {
    id: 3,
    name: "Denim Jeans",
    description: "Classic blue denim jeans with perfect fit",
    price: 75000,
    stock: 66,
    image: "https://picsum.photos/200",
    createAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: 2,
    name: "Premium Hoodie",
    description: "Warm and stylish hoodie for cold weather",
    price: 50000,
    stock: 36,
    image: "https://picsum.photos/200",
    createAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: 1,
    name: "Basic T-Shirt",
    description: "Comfortable cotton t-shirt for everyday wear",
    price: 25000,
    stock: 86,
    image: "https://picsum.photos/200",
    createAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: 5,
    name: "Leather Jacket",
    description: "Stylish black leather jacket",
    price: 250000,
    stock: 20,
    image: "https://picsum.photos/200",
    createAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: 6,
    name: "Sneakers",
    description: "Comfortable white sneakers with rubber sole",
    price: 120000,
    stock: 50,
    image: "https://picsum.photos/200",
    createAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: 7,
    name: "T-Shirt",
    description: "Basic white cotton t-shirt",
    price: 30000,
    stock: 100,
    image: "https://picsum.photos/200",
    createAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: 8,
    name: "Hoodie",
    description: "Gray fleece hoodie with front pocket",
    price: 95000,
    stock: 40,
    image: "https://picsum.photos/200",
    createAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: 9,
    name: "Baseball Cap",
    description: "Blue baseball cap with adjustable strap",
    price: 20000,
    stock: 60,
    image: "https://picsum.photos/200",
    createAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: 10,
    name: "Sunglasses",
    description: "Polarized black sunglasses with UV protection",
    price: 80000,
    stock: 35,
    image: "https://picsum.photos/200",
    createAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: 11,
    name: "Backpack",
    description: "Durable black backpack with multiple compartments",
    price: 150000,
    stock: 25,
    image: "https://picsum.photos/200",
    createAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: 12,
    name: "Sweatpants",
    description: "Comfortable gray sweatpants",
    price: 60000,
    stock: 90,
    image: "https://picsum.photos/200",
    createAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: 13,
    name: "Formal Shoes",
    description: "Classic black leather formal shoes",
    price: 180000,
    stock: 15,
    image: "https://picsum.photos/200",
    createAt: new Date(),
    updateAt: new Date(),
  },
];
